-- Run this in the Supabase SQL editor after enabling Email auth.
-- It adds per-user ownership to PPL Prep data and enables row-level security.

create table if not exists public.quiz_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  score integer not null,
  total_questions integer not null,
  category text not null
);

create table if not exists public.question_results (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  question_id text not null,
  category text not null,
  correct boolean not null,
  session_id text not null
);

create table if not exists public.checklist_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  item_id text not null
);

alter table public.quiz_scores
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.question_results
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.checklist_items
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

create table if not exists public.oral_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null,
  question_count integer not null,
  transcript jsonb not null,
  summary text not null
);

create index if not exists quiz_scores_user_id_idx on public.quiz_scores(user_id);
create index if not exists question_results_user_id_idx on public.question_results(user_id);
create index if not exists checklist_items_user_id_idx on public.checklist_items(user_id);
create index if not exists oral_sessions_user_id_created_at_idx on public.oral_sessions(user_id, created_at desc);

create unique index if not exists checklist_items_user_item_idx
  on public.checklist_items(user_id, item_id);

alter table public.quiz_scores enable row level security;
alter table public.question_results enable row level security;
alter table public.checklist_items enable row level security;
alter table public.oral_sessions enable row level security;

drop policy if exists "Users can read own quiz scores" on public.quiz_scores;
drop policy if exists "Users can insert own quiz scores" on public.quiz_scores;
drop policy if exists "Users can update own quiz scores" on public.quiz_scores;
drop policy if exists "Users can delete own quiz scores" on public.quiz_scores;

create policy "Users can read own quiz scores"
  on public.quiz_scores for select
  using (auth.uid() = user_id);

create policy "Users can insert own quiz scores"
  on public.quiz_scores for insert
  with check (auth.uid() = user_id);

create policy "Users can update own quiz scores"
  on public.quiz_scores for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own quiz scores"
  on public.quiz_scores for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own question results" on public.question_results;
drop policy if exists "Users can insert own question results" on public.question_results;
drop policy if exists "Users can update own question results" on public.question_results;
drop policy if exists "Users can delete own question results" on public.question_results;

create policy "Users can read own question results"
  on public.question_results for select
  using (auth.uid() = user_id);

create policy "Users can insert own question results"
  on public.question_results for insert
  with check (auth.uid() = user_id);

create policy "Users can update own question results"
  on public.question_results for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own question results"
  on public.question_results for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own checklist items" on public.checklist_items;
drop policy if exists "Users can insert own checklist items" on public.checklist_items;
drop policy if exists "Users can update own checklist items" on public.checklist_items;
drop policy if exists "Users can delete own checklist items" on public.checklist_items;

create policy "Users can read own checklist items"
  on public.checklist_items for select
  using (auth.uid() = user_id);

create policy "Users can insert own checklist items"
  on public.checklist_items for insert
  with check (auth.uid() = user_id);

create policy "Users can update own checklist items"
  on public.checklist_items for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own checklist items"
  on public.checklist_items for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own oral sessions" on public.oral_sessions;
drop policy if exists "Users can insert own oral sessions" on public.oral_sessions;
drop policy if exists "Users can update own oral sessions" on public.oral_sessions;
drop policy if exists "Users can delete own oral sessions" on public.oral_sessions;

create policy "Users can read own oral sessions"
  on public.oral_sessions for select
  using (auth.uid() = user_id);

create policy "Users can insert own oral sessions"
  on public.oral_sessions for insert
  with check (auth.uid() = user_id);

create policy "Users can update own oral sessions"
  on public.oral_sessions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own oral sessions"
  on public.oral_sessions for delete
  using (auth.uid() = user_id);
