-- Run this in the Supabase SQL editor after enabling Email auth.
-- It adds per-user ownership to PPL Prep data and enables row-level security.

create table if not exists public.quiz_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  score integer not null,
  total_questions integer not null,
  category text not null
);

create table if not exists public.question_results (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  question_id text not null,
  category text not null,
  correct boolean not null,
  session_id text not null
);

create table if not exists public.checklist_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  item_id text not null
);

alter table public.quiz_scores
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.question_results
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.checklist_items
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

create table if not exists public.oral_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null,
  question_count integer not null,
  transcript jsonb not null,
  summary text not null
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  checkride_date date,
  preferred_aircraft text not null default 'Cessna 172S',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists checkride_date date;
alter table public.profiles add column if not exists preferred_aircraft text not null default 'Cessna 172S';
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

alter table public.oral_sessions add column if not exists session_key uuid;
alter table public.oral_sessions add column if not exists overall_score integer;
alter table public.oral_sessions add column if not exists readiness text;
alter table public.oral_sessions add column if not exists assessment jsonb;
alter table public.oral_sessions add column if not exists aircraft_model text;
alter table public.oral_sessions add column if not exists acs_version text not null default 'FAA-S-ACS-6C';

create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  session_key uuid,
  request_id text not null,
  request_kind text not null default 'oral_turn',
  model text not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  cache_creation_input_tokens integer not null default 0,
  cache_read_input_tokens integer not null default 0,
  estimated_cost_microusd bigint not null default 0
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, checkride_date, preferred_aircraft)
  values (
    new.id,
    nullif(new.raw_user_meta_data ->> 'display_name', ''),
    (nullif(new.raw_user_meta_data ->> 'checkride_date', ''))::date,
    coalesce(nullif(new.raw_user_meta_data ->> 'preferred_aircraft', ''), 'Cessna 172S')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
  after insert on auth.users
  for each row execute function public.handle_new_user_profile();

insert into public.profiles (id, display_name, preferred_aircraft)
select
  id,
  nullif(raw_user_meta_data ->> 'display_name', ''),
  coalesce(nullif(raw_user_meta_data ->> 'preferred_aircraft', ''), 'Cessna 172S')
from auth.users
on conflict (id) do nothing;

create index if not exists quiz_scores_user_id_idx on public.quiz_scores(user_id);
create index if not exists question_results_user_id_idx on public.question_results(user_id);
create index if not exists checklist_items_user_id_idx on public.checklist_items(user_id);
create index if not exists oral_sessions_user_id_created_at_idx on public.oral_sessions(user_id, created_at desc);
create unique index if not exists oral_sessions_session_key_idx on public.oral_sessions(session_key) where session_key is not null;
create index if not exists ai_usage_user_created_at_idx on public.ai_usage(user_id, created_at desc);
create index if not exists ai_usage_session_key_idx on public.ai_usage(session_key) where session_key is not null;

create unique index if not exists checklist_items_user_item_idx
  on public.checklist_items(user_id, item_id);

alter table public.quiz_scores enable row level security;
alter table public.question_results enable row level security;
alter table public.checklist_items enable row level security;
alter table public.oral_sessions enable row level security;
alter table public.profiles enable row level security;
alter table public.ai_usage enable row level security;

drop policy if exists "Users can read own quiz scores" on public.quiz_scores;
drop policy if exists "Users can insert own quiz scores" on public.quiz_scores;
drop policy if exists "Users can update own quiz scores" on public.quiz_scores;
drop policy if exists "Users can delete own quiz scores" on public.quiz_scores;

create policy "Users can read own quiz scores"
  on public.quiz_scores for select
  using (auth.uid() = user_id);

create policy "Users can insert own quiz scores"
  on public.quiz_scores for insert
  with check (auth.uid() = user_id);

create policy "Users can update own quiz scores"
  on public.quiz_scores for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own quiz scores"
  on public.quiz_scores for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own question results" on public.question_results;
drop policy if exists "Users can insert own question results" on public.question_results;
drop policy if exists "Users can update own question results" on public.question_results;
drop policy if exists "Users can delete own question results" on public.question_results;

create policy "Users can read own question results"
  on public.question_results for select
  using (auth.uid() = user_id);

create policy "Users can insert own question results"
  on public.question_results for insert
  with check (auth.uid() = user_id);

create policy "Users can update own question results"
  on public.question_results for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own question results"
  on public.question_results for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own checklist items" on public.checklist_items;
drop policy if exists "Users can insert own checklist items" on public.checklist_items;
drop policy if exists "Users can update own checklist items" on public.checklist_items;
drop policy if exists "Users can delete own checklist items" on public.checklist_items;

create policy "Users can read own checklist items"
  on public.checklist_items for select
  using (auth.uid() = user_id);

create policy "Users can insert own checklist items"
  on public.checklist_items for insert
  with check (auth.uid() = user_id);

create policy "Users can update own checklist items"
  on public.checklist_items for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own checklist items"
  on public.checklist_items for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own oral sessions" on public.oral_sessions;
drop policy if exists "Users can insert own oral sessions" on public.oral_sessions;
drop policy if exists "Users can update own oral sessions" on public.oral_sessions;
drop policy if exists "Users can delete own oral sessions" on public.oral_sessions;

create policy "Users can read own oral sessions"
  on public.oral_sessions for select
  using (auth.uid() = user_id);

create policy "Users can insert own oral sessions"
  on public.oral_sessions for insert
  with check (auth.uid() = user_id);

create policy "Users can update own oral sessions"
  on public.oral_sessions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own oral sessions"
  on public.oral_sessions for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read own profile" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;

create policy "Users can read own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Users can read own AI usage" on public.ai_usage;
drop policy if exists "Users can insert own AI usage" on public.ai_usage;

create policy "Users can read own AI usage"
  on public.ai_usage for select
  using (auth.uid() = user_id);

create policy "Users can insert own AI usage"
  on public.ai_usage for insert
  with check (auth.uid() = user_id);

create or replace function public.get_my_ai_usage_summary()
returns table (
  request_count bigint,
  input_tokens bigint,
  output_tokens bigint,
  estimated_cost_microusd bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    count(*)::bigint,
    coalesce(sum(input_tokens), 0)::bigint,
    coalesce(sum(output_tokens), 0)::bigint,
    coalesce(sum(estimated_cost_microusd), 0)::bigint
  from public.ai_usage
  where user_id = auth.uid();
$$;

grant execute on function public.get_my_ai_usage_summary() to authenticated;
