export type AcsOralQuestion = {
  id: string;
  acsArea: string;
  acsCode: string;
  topic: string;
  prompt: string;
  rubric: string[];
  hint: string;
  reference: string;
};

const q = (
  id: string,
  acsArea: string,
  acsCode: string,
  topic: string,
  prompt: string,
  rubric: string[],
  hint: string,
  reference: string
): AcsOralQuestion => ({ id, acsArea, acsCode, topic, prompt, rubric, hint, reference });

export const ACS_ORAL_QUESTIONS: AcsOralQuestion[] = [
  q("currency-passengers", "Pilot Qualifications", "PA.I.A.K1", "Currency and proficiency", "You have flown recently but have not carried passengers in several months. What must you verify before taking two friends on a day VFR flight, and why might legal currency still be insufficient?", ["Apply the passenger-carrying recent-experience rule", "Distinguish legal currency from proficiency", "Consider aircraft and avionics familiarity"], "Separate what makes the flight legal from what makes you personally ready.", "14 CFR 61.57; FAA-S-ACS-6C PA.I.A.K1 and PA.I.A.R1"),
  q("private-pilot-compensation", "Pilot Qualifications", "PA.I.A.K2", "Privileges and limitations", "A friend offers to pay all operating expenses if you fly both of you to a concert. As a private pilot, how would you decide whether this flight and expense arrangement are permitted?", ["Recognize private-pilot compensation limitations", "Discuss common purpose and pro-rata expense sharing", "Avoid acting as an air carrier or holding out"], "Start with who benefits from the trip and how expenses may legally be shared.", "14 CFR 61.113; FAA-S-ACS-6C PA.I.A.K2"),
  q("medical-fitness", "Pilot Qualifications", "PA.I.A.K3", "Medical fitness", "Your medical certificate is valid, but you developed a new condition and started an over-the-counter medication yesterday. How do you determine whether you may act as PIC today?", ["Recognize the prohibition on flying with a disqualifying condition or medication", "Use a personal fitness assessment", "Seek appropriate aeromedical guidance when uncertain"], "A valid certificate does not by itself guarantee fitness for this flight.", "14 CFR 61.53; FAA-S-ACS-6C PA.I.A.K3"),

  q("inoperative-equipment", "Airworthiness Requirements", "PA.I.B.K3a", "Inoperative equipment", "During preflight for a day VFR flight, you find an installed landing light inoperative. Walk me through the complete process you would use to determine whether the aircraft may be flown.", ["Check 14 CFR 91.205 and the aircraft's equipment requirements", "Check the type design, KOEL, MEL if applicable, and Airworthiness Directives", "Remove or deactivate and placard as required", "Make and document an airworthy decision rather than assuming day VFR makes it acceptable"], "Use the full inoperative-equipment decision process, not only the day-VFR equipment list.", "14 CFR 91.205 and 91.213; FAA-S-ACS-6C PA.I.B.K3"),
  q("aircraft-inspections", "Airworthiness Requirements", "PA.I.B.K1b", "Required inspections", "Before a rental flight, which inspection and maintenance records would you verify, and which requirements depend on how the aircraft is operated or equipped?", ["Verify annual inspection status", "Recognize when a 100-hour inspection applies", "Consider ELT and transponder requirements", "Distinguish VFR requirements from IFR pitot-static requirements", "Check Airworthiness Directives"], "Some inspections apply to every aircraft; others depend on the operation or equipment.", "14 CFR 39, 43, 91.207, 91.409, and 91.413; FAA-S-ACS-6C PA.I.B.K1"),
  q("aircraft-documents", "Airworthiness Requirements", "PA.I.B.K1a", "Aircraft documents", "Show me how you would verify the aircraft's required certificates and operating limitations before flight. Which items must be aboard, and which maintenance records normally remain on the ground?", ["Identify airworthiness and registration certificates", "Identify operating limitations and current weight-and-balance information", "Do not claim maintenance logbooks must be carried aboard", "Check certificate validity and applicability"], "Keep aircraft documents aboard separate from maintenance records used to prove inspection status.", "14 CFR 91.9 and 91.203; FAA-S-ACS-6C PA.I.B.K1"),

  q("weather-go-no-go", "Weather Information", "PA.I.C.R1", "Weather decision-making", "The destination is forecast marginal VFR near your personal minimums, with lowering ceilings along the route. Describe your briefing, go/no-go decision, and specific triggers for diverting or cancelling.", ["Use current and forecast weather for departure, route, and destination", "Apply personal minimums", "Identify observable diversion triggers", "Maintain an alternate plan and fuel margin"], "Turn the forecast into specific decision points rather than only saying you would monitor it.", "14 CFR 91.103; FAA-S-ACS-6C PA.I.C.R1"),
  q("convective-weather", "Weather Information", "PA.I.C.K2g", "Convective weather", "A Convective SIGMET affects part of your planned VFR route, but your weather app shows a possible gap between cells. How would you evaluate and manage this situation?", ["Recognize the hazards of thunderstorms and embedded or developing cells", "Explain limitations and latency of displayed weather", "Avoid using a perceived gap for close tactical penetration", "Choose a conservative delay, reroute, or cancellation"], "Displayed radar is strategic information and may not show the weather's current exact position.", "AIM Chapter 7; FAA-S-ACS-6C PA.I.C.K2g and PA.I.C.R2"),
  q("onboard-weather", "Weather Information", "PA.I.C.R2a", "Onboard weather limitations", "Your datalink display looks clear ahead while the view outside is deteriorating. Which source should drive your immediate decision, and what limitations of onboard weather must you consider?", ["Prioritize real-time visual and aircraft indications", "Recognize datalink age and processing latency", "Use onboard weather strategically rather than tactically", "Divert before options narrow"], "Compare the age of the picture on the screen with what the aircraft is encountering now.", "AIM Chapter 7; FAA-S-ACS-6C PA.I.C.R2"),

  q("fuel-recalculation", "Cross-Country Flight Planning", "PA.I.D.S4", "Fuel planning", "Halfway through a VFR cross-country, the groundspeed is lower and fuel burn is higher than planned. Explain how you recalculate the remaining fuel and decide whether to continue or divert.", ["Recalculate time remaining using actual groundspeed", "Use actual fuel burn and usable fuel remaining", "Protect the applicable legal reserve", "Include a practical safety margin and divert early"], "Rebuild the estimate from actual time, burn, and usable fuel rather than the original plan.", "14 CFR 91.151; FAA-S-ACS-6C PA.I.D.K3c and PA.I.D.S4"),
  q("route-altitude", "Cross-Country Flight Planning", "PA.I.D.K2", "Route and altitude", "How would you select a VFR cruise altitude for a route with rising terrain, scattered clouds, and a crosswind? Include both regulatory and risk-management considerations.", ["Apply VFR cruising-altitude rules when applicable", "Maintain terrain and obstacle clearance", "Consider glide options, clouds, wind, and airspace", "Adjust the route or altitude as conditions change"], "The magnetic course rule is only one part of a safe altitude decision.", "14 CFR 91.119 and 91.159; FAA-S-ACS-6C PA.I.D.K2"),
  q("vfr-flight-plan", "Cross-Country Flight Planning", "PA.I.D.K5", "VFR flight plans", "What does filing a VFR flight plan accomplish, and what must you do after filing so it actually provides its intended search-and-rescue benefit?", ["Explain that a VFR flight plan is not an ATC clearance or flight-following service", "Activate the flight plan", "Close it after arrival", "Update or communicate when the plan changes significantly"], "Distinguish Flight Service search-and-rescue tracking from ATC radar services.", "AIM Chapter 5; FAA-S-ACS-6C PA.I.D.K5"),

  q("class-c-transition", "National Airspace System", "PA.I.E.K1", "Class C operations", "You plan to transition through Class C airspace. What communication and equipment requirements apply, and exactly when have you established the required two-way communication?", ["Establish two-way radio communication before entry", "Recognize communication is established when ATC responds with the aircraft call sign", "Meet transponder and ADS-B requirements where applicable", "Comply with ATC instructions or remain clear"], "A generic standby response is different from ATC using your aircraft call sign.", "14 CFR 91.130, 91.215, and 91.225; FAA-S-ACS-6C PA.I.E.K1"),
  q("class-d-weather", "National Airspace System", "PA.I.E.S1", "Airspace and weather minimums", "The reported ceiling at a Class D airport is 900 feet with three miles visibility. Can you enter and land under normal VFR? Explain the applicable requirements and alternatives.", ["Recognize the basic VFR ceiling requirement for surface-controlled airspace", "Apply Class D VFR weather minimums", "Discuss Special VFR only as a separate ATC clearance with its requirements", "Make a safe decision rather than treating legal minimums as a target"], "Consider both the definition of basic VFR and the visibility-and-cloud-clearance rules.", "14 CFR 91.155 and 91.157; FAA-S-ACS-6C PA.I.E.K4 and PA.I.E.S1"),
  q("tfr-check", "National Airspace System", "PA.I.E.K3", "Temporary flight restrictions", "Your route passes near a stadium and an active wildfire. How will you determine whether a TFR affects the flight, and what will you do if your electronic chart has not refreshed?", ["Check current NOTAM and TFR information during preflight", "Do not rely solely on stale chart data", "Understand that different TFRs have different dimensions and requirements", "Reroute or obtain required authorization before entry"], "TFR information is time-sensitive and must come from a current source.", "14 CFR 91.103 and 91.137 through 91.145; FAA-S-ACS-6C PA.I.E.K3"),

  q("density-altitude", "Performance and Limitations", "PA.I.F.K2a", "Density altitude", "You are departing a short, high-elevation runway on a hot afternoon near maximum gross weight. Explain what changes in performance and how you determine whether the takeoff has an acceptable margin.", ["Recognize reduced engine, propeller, and aerodynamic performance", "Use the applicable POH performance chart with current conditions", "Account for runway, wind, slope, surface, and obstacles", "Add a conservative margin for real-world performance"], "High density altitude affects more than takeoff roll alone.", "POH/AFM; FAA-S-ACS-6C PA.I.F.K2 and PA.I.F.R3"),
  q("aft-cg", "Performance and Limitations", "PA.I.F.K2e", "Center of gravity", "Your weight is below maximum, but the calculated center of gravity is aft of limits. Why is the aircraft not airworthy for this flight, and what handling and recovery risks would you expect?", ["Recognize that both weight and CG must remain within limits", "Describe reduced longitudinal stability", "Describe stall or spin recovery concerns", "Correct the loading before flight"], "Being under maximum gross weight does not make an out-of-envelope loading acceptable.", "POH/AFM; FAA-S-ACS-6C PA.I.F.K2e and PA.I.F.S1"),
  q("performance-margin", "Performance and Limitations", "PA.I.F.R3", "Calculated versus actual performance", "The POH chart predicts enough distance to clear an obstacle with only a small margin. Why might actual performance differ, and how would that affect your decision?", ["Recognize chart assumptions and test-aircraft condition", "Consider pilot technique and aircraft condition", "Consider weather, runway, and measurement uncertainty", "Reject a plan that depends on near-perfect book performance"], "List the assumptions behind the chart and decide what happens when several are slightly unfavorable.", "POH/AFM; FAA-S-ACS-6C PA.I.F.R1 and PA.I.F.R3"),

  q("electrical-failure", "Operation of Systems", "PA.I.G.K1f", "Electrical system", "In your {aircraft}, the low-voltage indication appears in cruise. Explain what the indication may mean, what equipment could eventually be affected, and how you would respond without inventing aircraft-specific checklist steps.", ["Recognize a possible charging-system failure", "Monitor electrical indications and shed nonessential load as directed", "Use the applicable POH checklist", "Plan a prompt landing before battery power is depleted", "Avoid inventing model-specific values or switch sequences"], "Explain the system-level problem first, then defer exact switch actions and values to the POH.", "Applicable POH/AFM; FAA-S-ACS-6C PA.I.G.K1f and PA.I.G.K2"),
  q("pitot-static", "Operation of Systems", "PA.I.G.K1h", "Pitot-static system", "Compare the likely instrument indications from a blocked pitot opening, a blocked static source, and an alternate static source. How would you manage an abnormal indication in your aircraft?", ["Relate pitot pressure to airspeed indications", "Relate static pressure to airspeed, altimeter, and vertical-speed indications", "Use the aircraft checklist and alternate source if equipped", "Cross-check instruments and avoid fixation"], "Work from which instruments use pitot pressure, static pressure, or both.", "Applicable POH/AFM; FAA-S-ACS-6C PA.I.G.K1h and PA.I.G.R1"),
  q("fuel-system", "Operation of Systems", "PA.I.G.K1e", "Fuel system", "Describe the fuel system in your {aircraft}, including usable fuel, tank selection, indications, vents, drains, and the consequences of mismanagement. Which details must be verified in your exact POH?", ["Describe the aircraft's fuel flow and controls without unsupported specifics", "Distinguish total from usable fuel", "Discuss vents, drains, contamination, and indications", "Identify fuel exhaustion, starvation, and imbalance risks", "Verify model and configuration details in the POH"], "Trace fuel from each tank to the engine and identify every place the pilot makes a decision.", "Applicable POH/AFM; FAA-S-ACS-6C PA.I.G.K1e"),

  q("external-pressure", "Human Factors", "PA.I.H.R2", "Hazardous attitudes", "Passengers are waiting and a nonrefundable reservation creates pressure to depart into worsening weather. Identify the hazardous attitudes or biases at work and describe a concrete way to interrupt them.", ["Recognize external pressure and get-there-itis", "Identify confirmation or expectation bias", "Use a structured risk tool or personal minimums", "Create an alternate plan and communicate it before departure"], "Name both the mental trap and a practical countermeasure.", "FAA-H-8083-2; FAA-S-ACS-6C PA.I.H.R2 and PA.I.H.R4"),
  q("hypoxia-hyperventilation", "Human Factors", "PA.I.H.K1", "Aeromedical recognition", "A passenger becomes lightheaded with tingling fingers while flying at altitude. Compare hypoxia and hyperventilation, and explain the safest immediate response when you are uncertain which is occurring.", ["Recognize overlapping symptoms", "Provide supplemental oxygen if available", "Control breathing without delaying a descent", "Descend and land for evaluation if symptoms persist"], "When two conditions look similar, choose actions that address the most serious possibility safely.", "AIM Chapter 8; FAA-S-ACS-6C PA.I.H.K1"),
  q("medication-fatigue", "Human Factors", "PA.I.H.K3", "Medication and fatigue", "You slept poorly and took a new cold medication that says it may cause drowsiness. How do you evaluate fitness for flight even if no regulation names that exact product?", ["Use a personal fitness checklist such as IMSAFE", "Recognize combined fatigue and medication effects", "Do not self-test an unfamiliar medication while flying", "Delay the flight and seek reliable medical guidance"], "Legal eligibility and sound aeromedical decision-making are separate questions.", "14 CFR 61.53 and 91.17; FAA-S-ACS-6C PA.I.H.K3"),

  q("soft-tire", "Preflight Assessment", "PA.II.A.K3", "Preflight defect", "During preflight of your {aircraft}, one main tire appears noticeably softer than the other. What do you do, and what sources support your airworthiness decision?", ["Stop and investigate rather than judging only by appearance", "Use the POH or maintenance data for acceptable condition or pressure", "Have an appropriately authorized person address a discrepancy when required", "Do not fly until the aircraft is determined airworthy"], "A no-go decision is a start; explain how you verify the defect and return the aircraft to an airworthy condition.", "Applicable POH/AFM and maintenance data; FAA-S-ACS-6C PA.II.A.K3"),
  q("fuel-contamination", "Preflight Assessment", "PA.II.A.K3c", "Fuel contamination", "A fuel sample contains water, and a second sample is still contaminated. Describe your next actions and the risks of simply draining until one sample looks clear.", ["Continue investigating all sumps and the source of contamination", "Recognize water can migrate or remain trapped", "Follow the aircraft checklist and maintenance guidance", "Do not depart until contamination is resolved and the aircraft is airworthy"], "One clear sample does not necessarily explain or eliminate the source of repeated contamination.", "Applicable POH/AFM; FAA-S-ACS-6C PA.II.A.K3"),
  q("pave-assessment", "Preflight Assessment", "PA.II.A.R1", "Integrated risk assessment", "The airplane is legal, weather is marginal but acceptable, you slept poorly, and you feel pressure to arrive on time. Use a structured process to make and explain the go/no-go decision.", ["Assess pilot, aircraft, environment, and external pressures", "Recognize interacting risks rather than evaluating each in isolation", "Apply personal minimums", "Choose mitigation that genuinely reduces risk, including delaying or cancelling"], "Risk factors compound; do not treat each yellow flag as independent.", "FAA-H-8083-2; FAA-S-ACS-6C PA.II.A.R1 through R4"),

  q("passenger-briefing", "Flight Deck Management", "PA.II.B.K1", "Passenger briefing", "Give the passenger briefing you would use before a local flight, including normal operations, passenger conduct, propeller safety, and emergencies.", ["Identify the PIC and set passenger expectations", "Cover belts, shoulder harnesses, doors, and exits", "Cover sterile-cockpit and passenger conduct", "Address propeller avoidance and emergency actions"], "Think beyond seat belts: cover the cabin, conduct, hazards outside, and emergencies.", "14 CFR 91.107; FAA-S-ACS-6C PA.II.B.K1 and PA.II.B.S2"),
  q("efb-failure", "Flight Deck Management", "PA.II.B.R1", "Automation and EFB management", "Your tablet overheats and shuts down shortly after departure on a cross-country. Explain how you continue safely and what preflight preparation should have prevented this from becoming an emergency.", ["Maintain aircraft control and situational awareness", "Use current backup navigation information", "Plan power, heat, mounting, and database currency", "Avoid overreliance on a single device", "Land or divert if navigation confidence is inadequate"], "Describe both the immediate response and the redundancy you should have prepared before takeoff.", "AIM; FAA-S-ACS-6C PA.II.B.K3 and PA.II.B.R1"),
  q("loose-cargo", "Flight Deck Management", "PA.II.B.K4", "Cargo and distractions", "Just before takeoff you notice a heavy bag is unsecured behind a passenger and a phone is loose near the rudder pedals. What risks do these create, and how do you correct them?", ["Secure cargo for normal and emergency loads", "Prevent flight-control interference", "Manage passenger belongings before movement", "Delay departure until the flight deck is orderly"], "Consider what each object could do during turbulence, braking, or an abrupt maneuver.", "14 CFR 91.13; FAA-S-ACS-6C PA.II.B.K4 and PA.II.B.R3"),
];

export function personalizeQuestion(question: AcsOralQuestion, aircraft: string) {
  return { ...question, prompt: question.prompt.replaceAll("{aircraft}", aircraft) };
}

function seededValue(seed: string, value: string) {
  let hash = 2166136261;
  for (const char of `${seed}:${value}`) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619);
  return hash >>> 0;
}

export function selectAcsQuestions(questionCount: number, seed: string, weakCodes: string[] = []) {
  const weakPrefixes = new Set(weakCodes.map((code) => code.split(".").slice(0, 3).join(".")));
  const ordered = [...ACS_ORAL_QUESTIONS].sort((a, b) => {
    const aWeak = weakPrefixes.has(a.acsCode.split(".").slice(0, 3).join(".")) ? 1 : 0;
    const bWeak = weakPrefixes.has(b.acsCode.split(".").slice(0, 3).join(".")) ? 1 : 0;
    return bWeak - aWeak || seededValue(seed, a.id) - seededValue(seed, b.id);
  });

  const selected: AcsOralQuestion[] = [];
  const usedAreas = new Set<string>();
  for (const question of ordered) {
    if (!usedAreas.has(question.acsArea)) {
      selected.push(question);
      usedAreas.add(question.acsArea);
      if (selected.length === questionCount) return selected;
    }
  }
  for (const question of ordered) {
    if (!selected.some((item) => item.id === question.id)) selected.push(question);
    if (selected.length === questionCount) break;
  }
  return selected;
}

export function findAcsQuestion(id: string) {
  return ACS_ORAL_QUESTIONS.find((question) => question.id === id);
}
